version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ledm-nginx
    ports:
      - "4444:4444"
    networks:
      - site-network

networks:
  site-network:
    driver: bridge